# Generated by Django 3.2.7 on 2021-10-03 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0007_auto_20210912_0122'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monthlybudget',
            name='income',
            field=models.FloatField(),
        ),
    ]
